version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run Tests
          command: yarn test

      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
            sudo apt-get update
            sudo apt-get -qq install git-ftp
            echo "'_$(git status -uno --porcelain | wc -l)_'"
            git status -uno --porcelain
            echo "Initiating Push site:mastro-elfo.it."
            git ftp init --user "$username" --passwd "$password" ftp.mastro-elfo.it/all-about-test/
            else
              echo "Not master branch so not deploying"
            fi
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test
